name: Build FFmpeg-Kit Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'release/**'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Build Tools
        run: |
          brew install autoconf automake libtool pkg-config cmake nasm gnu-sed
          
      - name: Build iOS XCFramework (HTTPS Variant)
        run: |
          ./ios.sh \
            --xcframework \
            --enable-ios-https \
            --enable-ios-audiotoolbox \
            --enable-ios-videotoolbox \
            --enable-ios-zlib \
            --no-clean
          
      - name: Build Android (HTTPS Variant)
        run: |
          ./android.sh \
            --enable-android-https \
            --enable-android-zlib \
            --api-level=24
          
      - name: Package Binaries
        run: |
          mkdir -p artifacts
          cp -r prebuilt/bundle-apple-xcframework-ios artifacts/ios
          cp prebuilt/bundle-android-*/ffmpeg-kit-*.zip artifacts/
          tar czvf ffmpeg-kit-binaries.tar.gz artifacts/
          
      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-kit-binaries
          path: ffmpeg-kit-binaries.tar.gz
          
